### ISSUE TITLE
Start module hidden.

### ISSUE THREAD

**Issue by Snille** [CatoAntonsen/MMM-MotionEye#6]
Hi!
As you know I have 6 streams. And they are all "motion-activated".
When I reload/restart the mirror, all MotionEye modules (Headers) are "shown" even if there is no movements, the header stays shown until there is a movement (in each module) or I manually "hide" the module(s).
I think it would be good if there where an option to start the module "hidden". :)

**Comment by CatoAntonsen** [comment]
I'll have a look at it this weekend.

**Comment by CatoAntonsen** [comment]
This should be fixed in version 1.5.0. :)

**Comment by Snille** [comment]
Hi, can't get it to work... 
In the log it says:
```
0|mm       | Hiding camera: 5
0|mm       | Hiding camera: 3
0|mm       | Hiding camera: 6
0|mm       | Hiding camera: 1
0|mm       | Hiding camera: 2
```
This is my conf (for all 5 cameras)...
```
		{
			module: 'MMM-MotionEye',
			position: 'bottom_left',
			classes: "default everyone",
			header: "Holk 1",
			config: {
				id: 1,
				url: "http://10.0.0.136:8081",
				autoHide: true,
				autoHideDelay: 30000,
				width: "340px",
				debug: true,
			}
		},
``` 
But on the MM the "headers" are still shown until a motion has happened and the timer has passed. :)

**Comment by CatoAntonsen** [comment]
That is strange since it seems to work for me. But I only have 1 camera.

Can you try to remove 4 of the 5 camera in config.js and try again?

**Comment by CatoAntonsen** [comment]
Btw, I'm in the process of setting up a new MotionEye installation. Do you get all your streams for 1 MotionEye installation or multiple?

**Comment by Snille** [comment]
Hmm... Even with only one camera (the one above), the header shows up (but not the picture, same as before)... I have lot's of modules going. Maybe there is another one that creates the problem. I'll have to try on another installation to see of that helps. :) I'll do it during the day and get back to you.

My setup is one "main" Ubuntu server with MotionEye on a VM (actually a LXC if you know what it is.. :). That is the HUB.
Then I have 3 network-cameras. Attached to the HUB. Then the 3 "Holk" cameras are all MotionEyeOS on Rpi-Zeros connected to the HUB as well. :)

**Comment by CatoAntonsen** [comment]
Yeah, it might be a good idea to remove other modules to rule that out. Not saying I'm perfect, but ... ;-)

I haven't been working with containers, yet. But it seems very interesting! :)

When you configure MM, do you use the camera URL's pointing to the "hub" or directly to the Pi Zero's?

**Comment by Snille** [comment]
On the network cameras, I use the HUB:s IP (the "stream" link in MotionEye). For the RPi-Zeros, I use their own IPs (the "stream" url in each MotionEyeOS).  :)

**Comment by Snille** [comment]
Ok, done some testing..
With only your module and "Remote-Control" (I need that one to do restarts easier... :).
So, with one camera all works good.
With two cameras the cameras gets hidden but I get errors in the console (same one two times).
```
Uncaught TypeError: Cannot read property 'debug' of undefined
    at Class.socketNotificationReceived (MMM-MotionEye.js:78)
```
With three cameras sometimes all three gets hidden, sometimes only two. 
And I get the same error 5 times... :)

**Comment by CatoAntonsen** [comment]
Ok, I think I found the bug. Actually several ones. Version 1.5.1 in now checked in. Please let me know after testing more :)

**Comment by Snille** [comment]
Yes! Working! Thank you! :)
